server, ignore graceful shutdown timeout
pixelfederation/swoole-bundle pull request #247
Opened 2023-03-31 13:05 UTC by pistej

#239

2023-03-31 15:00 UTC, Rastusik commented
@pistej https://www.conventionalcommits.org/en/v1.0.0/

2023-03-31 15:48 UTC, pistej commented
hope commit message is ok :)

2023-04-07 23:33 UTC, Rastusik requested changes

2023-04-07 23:33 UTC, Rastusik commented on src/Server/HttpServer.php
> +    private function killSignalShutdown(int $masterPid): void
please rename to immediateSignalShutdown

2023-04-11 10:04 UTC, pistej commented on src/Server/HttpServer.php
> +    private function killSignalShutdown(int $masterPid): void
renamed

2023-04-11 10:05 UTC, pistej commented
not sure what job `releaser-dry-run` do and if fix shoud be on my side ... ?!

2023-04-11 10:42 UTC, Rastusik approved these changes

2023-04-11 10:42 UTC, Rastusik commented
@pistej no, please ignore the releaser script, it's broken and behaves non deterministically, so I was not able to fix it yet

2023-04-12 07:19 UTC, Rastusik requested changes

2023-04-12 07:19 UTC, Rastusik commented on tests/Feature/SwooleServerStartStopCommandTest.php
> +            $client = HttpClient::fromDomain('localhost', 9999, false);
I believe you have to measure how much time has passed here

2023-04-12 11:14 UTC, pistej commented on tests/Feature/SwooleServerStartStopCommandTest.php
> +            $client = HttpClient::fromDomain('localhost', 9999, false);
each server shutdown takes few milisecond, not sure what to measure ... tried get somehow signal number but no success ... need help

2023-04-12 15:28 UTC, Rastusik commented on tests/Feature/SwooleServerStartStopCommandTest.php
> +            $client = HttpClient::fromDomain('localhost', 9999, false);
maybe just measure that the shutdown process took less than 1 second? or 500 ms?

2023-04-13 20:52 UTC, Rastusik commented
@pistej can you please rebase this branch on develop? I hope I fixed the failing code coverage job

2023-04-14 11:28 UTC, pistej commented on tests/Feature/SwooleServerStartStopCommandTest.php
> +            $client = HttpClient::fromDomain('localhost', 9999, false);
shutdown process in booth cases takes approx 0.1 sec, .... but terminate wait until all tasks/request are done and --no-delay (kill) no, so I updated test if long request is terminated, --no-delay is called

2023-04-14 11:30 UTC, pistej commented
rebased, seems working .... so with each push I need to wait for you to approve docker bake job and so on?? is this good solution?

2023-04-14 11:47 UTC, Rastusik submitted a review, later dismissed

2023-04-14 11:50 UTC, Rastusik commented
yes, sorry, it's like this. this is inherited from the original k911 repository and pipeline and it is supposed to be for security reasons (https://circleci.com/blog/protect-secrets-with-restricted-contexts/). If you would like to contribute more, I can promote you to a team member, so that way you wouldn't need to wait for the approval.

2023-04-14 11:56 UTC, pistej commented
yea, It would be fine to allow it for me, at least for now as Im adding new features, thx. ... to see whats failed ...

2023-04-14 12:05 UTC, Rastusik commented
@pistej done. feel free to push code directly into this repository, this way you will get rid of the need for  approval

2023-04-19 07:57 UTC, Rastusik approved these changes

2023-04-19 07:59 UTC, Rastusik commented
@pistej please rebase onto current develop and I'll do the rest.

2023-04-19 07:59 UTC, Rastusik commented
and thank you for the contribution! :)

2023-04-19 08:16 UTC, pistej commented
done, but why still rebase ??

2023-04-19 08:28 UTC, Rastusik commented
because this repo has linear history without merge commits and GH UI won't allow me to rebase because of conflicts. this is inherited from the original repo and since you are the first one who creates multiple requests, this has not been an issue before

2023-04-19 08:30 UTC, Rastusik approved these changes

2023-04-19 08:30 UTC, merged