feat: dump non-reloadable files included before server start - for lo…
pixelfederation/swoole-bundle pull request #252
Opened 2023-04-05 21:09 UTC by pistej

…cal development (docker entrypoint)

#250

2023-04-20 13:19 UTC, Rastusik requested changes
@pistej first of all, thank you for the contribution! :) I think it's really great to be able to use HMR fully in the future! ;) 

Please make the mentioned changes and I'll do the rest ;)

2023-04-20 13:19 UTC, Rastusik commented on src/Server/Runtime/IncludedFiles.php
> +        if (!empty($runtimeConfiguration['nonReloadableFiles'])) {
I don't see where this configuration parameter is defined or filled in

2023-04-20 13:19 UTC, Rastusik commented on src/Server/Runtime/IncludedFiles.php
> +        \file_put_contents($this->cacheDir.'/nonReloadableFiles.txt', \implode("\n", $allFiles));
please use SF Filesystem wrapper

2023-04-20 13:19 UTC, Rastusik commented on src/Server/Runtime/IncludedFiles.php
> +        $appFiles = \array_filter($allFiles, fn ($values) => !(\str_contains($values, '/vendor/') || \str_starts_with($values, $this->kernelCacheDir)));
why are there two files? it would be easier to filter out the vendor and cache files directly in the $allFiles array and have just one file to be monitored by the watch script, wouldn't it?

2023-04-20 13:19 UTC, Rastusik commented on tests/Unit/Server/Runtime/IncludedFilesTest.php
> +        $includeFiles = new IncludedFiles('', '', self::NON_RELOADABLE_EXISTING_FILES);
this constructor feature is not usable from the symfony scope as it is implemented in the bundle right now, please remove it. it is also not a good practise to run logic in class constructor, especially I/O logic

2023-04-20 13:19 UTC, Rastusik commented on tests/Unit/Server/Runtime/IncludedFilesTest.php
> +        self::assertFileDoesNotExist(self::NON_EXISTING_FILE);
which real test scenario is this test testing? I think it is another candidate for removal

2023-04-20 13:19 UTC, Rastusik commented on tests/Unit/Server/Runtime/IncludedFilesTest.php
> +        $includeFiles->boot(['nonReloadableFiles' => self::NON_RELOADABLE_EXISTING_FILES]);
again - this feature is not usable anywhere in the bundle, just in this test. I suggest to remove it (the feature and the test) and just work with the result of `get_included_files()` which will definitely give you correct files

2023-04-20 13:19 UTC, Rastusik commented on tests/Unit/Server/Runtime/includedFiles/dummyCacheFile
I think this file is not needed

2023-05-03 11:01 UTC, pistej commented on docs/configuration-reference.md
> +    included_files: false
@Rastusik not fully understand your suggested conf. structure

1.  add 4. option ` hmr: dump_included_files` ?

 OR:

2. 

```yaml
hmr:
  dump_included_files:
      enabled: true
      file_path: '/var/www/'
```

2023-05-03 11:16 UTC, pistej commented on src/Server/Runtime/IncludedFiles.php
> +        $appFiles = \array_filter($allFiles, fn ($values) => !(\str_contains($values, '/vendor/') || \str_starts_with($values, $this->kernelCacheDir)));
first file is with all `get_included_files()` to check and perform hard reload, all files are needed, composer install/update can be performed or SF cache rebuilded, ... second file is for, to check this files with php lint, you can have files in invalid state and swoole server will not start and u dont want vendor, cache files (they should be always valid, shorter time to check those files and strat server)

2023-05-03 13:58 UTC, pistej commented on docs/docker-usage.md
> +if [[ $ENV == "test" || $ENV == "development" ]]; then
@Rastusik think all other changes from review are applied except this entrypoint, will test it little bit and commit here

2023-05-12 14:14 UTC, Rastusik commented on src/Server/Runtime/IncludedFiles.php
> +        $appFiles = \array_filter($allFiles, fn ($values) => !(\str_contains($values, '/vendor/') || \str_starts_with($values, $this->kernelCacheDir)));
OK, I see, thanks for clarification.

2023-05-12 14:19 UTC, Rastusik commented on src/Server/Runtime/IncludedFiles.php
> +        \file_put_contents($this->cacheDir.'/nonReloadableFiles.txt', \implode("\n", $allFiles));
I think there was a unit test before and you deleted it. It is not mandatory but you still could have injected the FS object and keep the unit test with a mocked FS injection... 

Either add the test or feel free to resolve this issue :)

2023-05-12 14:22 UTC, Rastusik requested changes
Sorry for late feedback. Would you please address the new comments? Thank you! :)

Also please address problems from this test run: https://app.circleci.com/pipelines/github/pixelfederation/swoole-bundle/1156/workflows/6a3b8d4f-3820-41ae-9c41-821cb53dec5f/jobs/17664

just disable the tests if xdebug is enabled, that should be sufficient

2023-05-19 11:31 UTC, pistej commented on docs/configuration-reference.md
> +    included_files: false
OR
```yaml
hmr:
  enabled: auto # |off|inotify|dump_included_files
  file_path: '/var/www/'
```
seems better

2023-05-19 14:27 UTC, Rastusik approved these changes

2023-05-19 14:59 UTC, merged

2023-05-19 14:59 UTC, Rastusik commented
@pistej thanks again for the contribution! ;)