feat(access-log): added possibility to enable access logging for http…
pixelfederation/swoole-bundle pull request #261
Opened 2023-04-11 21:37 UTC by pistej

… kernel handler and set custom log format

Issue: #251

2023-04-24 18:43 UTC, Rastusik requested changes
@pistej thank you for the contribution! :) 

I have some questions regarding this PR:
1) why do you need access logs directly from swoole? Don't you use nginx before swoole?
2) is this supposed to be used in prod environments or just for development? 
3) why are you using multiple request/response classes instead of one unified tuple from one of the frameworks?

2023-04-24 18:43 UTC, Rastusik commented on src/Bridge/Symfony/HttpKernel/HttpKernelRequestHandler.php
> +    private function logHttpFoundationRequest(SwooleRequest $request, SymfonyResponse $symfonyResponse): void
This code should go into a decorator layer, either decorating the request handler and therefore would need to log swoole response instead of symfony response, or decorating the http kernel.

2023-04-24 18:43 UTC, Rastusik commented on src/Bridge/Symfony/HttpKernel/HttpKernelRequestHandler.php
> +        if ($this->formatter instanceof NullFormatter) {
This condition doesn't make sense, if null logger is injected, there is no reason to call return

2023-04-24 18:43 UTC, Rastusik commented on src/Bridge/Symfony/HttpKernel/HttpKernelRequestHandler.php
> +        $message = $this->formatter->format(
Why is the formatter not configured in the monolog configuration? There should be no formatter here

2023-04-24 18:43 UTC, Rastusik commented on src/Bridge/Symfony/Log/AccessLogDataMap.php
> +        $headers = ['x-real-ip', 'client-ip', 'x-forwarded-for'];
This code could be reused from st request

2023-04-24 21:14 UTC, pistej commented
> @pistej thank you for the contribution! :)
> 
> I have some questions regarding this PR:
> 
> 1. why do you need access logs directly from swoole? Don't you use nginx before swoole?
> 2. is this supposed to be used in prod environments or just for development?
> 3. why are you using multiple request/response classes instead of one unified tuple from one of the frameworks?

@Rastusik 
1. a lot of apps are internal, on internal network, without communicating to outside, so there is no nginx or other proxy ... this log format aim to replace apache access logs which we use and parse/store ...
2. yes, all, used from local development, staging/testing env to production env
3. same logic was used in lib mezzio-swoole, whole mapper, formatter is just taken from this lib, idea was to use same classes for better porting new changes from original lib ... yes now see there is swoole request, sf response .... think, it can be somehow reworked to use only one way

2023-05-12 15:14 UTC, Rastusik requested changes

2023-05-12 15:14 UTC, Rastusik commented on docs/swoole-access-logs.md
> +      $format: "%%message%% %%context%% %%extra%%\n"
I suggest creating the definition of the formatter when access logging is enabled and just mention the formatter service in the monolog configuration

2023-05-12 15:14 UTC, Rastusik commented on docs/swoole-access-logs.md
> +        $enabled: true
also use the proper logger channel, I suggest `swoole.access_log`

2023-05-12 15:14 UTC, Rastusik commented on docs/swoole-access-logs.md
> +      swoole:
I would change swoole to swoole_access_log whereever that makes sense

2023-05-12 15:14 UTC, Rastusik commented on src/Bridge/Symfony/HttpFoundation/AccessLogOnKernelTerminate.php
> +        private bool $enabled = false
please remove this flag. either this listener should be registered or not registered at all

2023-05-12 15:14 UTC, Rastusik commented on src/Bridge/Symfony/HttpFoundation/AccessLogOnKernelTerminate.php
> +        private LoggerInterface $swooleLogger,
`$accessLogLogger` seems more appropriate to me, what do you think?

2023-05-12 15:14 UTC, Rastusik commented on docs/swoole-access-logs.md
> +        $enabled: true
just in case, I meant this:

```
    tags:
      - { name: monolog.logger, channel: swoole.access_log }
```

2023-05-12 15:14 UTC, Rastusik commented on src/Bridge/Symfony/HttpFoundation/AccessLogOnKernelTerminate.php
> +            $this->swooleLogger->reset();
this should be handled by Symfony - is it not?

2023-05-12 15:38 UTC, pistej commented on docs/swoole-access-logs.md
> +          $format: !php/const K911\Swoole\Bridge\Log\AccessLogFormatter::FORMAT_COMMON_TIME
how configured? like add this into `swoole.yaml` or `services.yaml`?

2023-05-12 16:06 UTC, Rastusik commented on src/Bridge/Symfony/HttpFoundation/AccessLogOnKernelTerminate.php
> +            $this->swooleLogger->reset();
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L114

2023-05-27 13:14 UTC, pistej commented on docs/swoole-access-logs.md
> +      $format: "%%message%% %%context%% %%extra%%\n"
updated little bit

2023-05-29 09:16 UTC, Rastusik approved these changes

2023-05-29 09:16 UTC, merged