Symfony6
pixelfederation/swoole-bundle pull request #27
Opened 2022-06-25 14:23 UTC by ChadSikorra

There's a couple things being done here:

* I removed the composer.lock. There's no good reason to have it committed for a bundle that I can think of. Looking at other popular Symfony Bundles, I do not see this being done.
* I updated the composer dependencies to allow Symfony ^6.0. This is a little loose. But it's either that or start adding each version up until another LTS I guess.
* Fixed HttpClient deprecations as in PHP 8.1+ the `\Serializable` interface is deprecated.

2022-06-25 14:24 UTC, ChadSikorra commented on composer.json
> +            "phpstan/extension-installer": true
Newer version of composer need this now for plugin execution.

2022-06-28 12:49 UTC, Rastusik requested changes
Hi @ChadSikorra :) thank you for your contribution. I will look into it, but I was unavailable recently. It seems like I will need to fix the travis pipeline for this to work... 

but the PRs have to be made against the `develop` branch, maybe that is the problem. Could you please change both of the PRs against develop? Thank you.

2022-06-28 12:49 UTC, Rastusik commented on src/Client/HttpClient.php
>          $this->client = self::makeSwooleClient($spec['host'], $spec['port'], $spec['ssl'], $spec['options']);
what is wrong with the json approach?

2022-06-30 01:43 UTC, ChadSikorra commented on src/Client/HttpClient.php
>          $this->client = self::makeSwooleClient($spec['host'], $spec['port'], $spec['ssl'], $spec['options']);
Nothing specifically, but the interface for Serializable was deprecated as of PH 8.1+. This just updates it per the migration guide. The magic methods for serialization don't require json and already supply array data.

2022-07-01 21:58 UTC, ChadSikorra commented
> Hi @ChadSikorra :) thank you for your contribution. I will look into it, but I was unavailable recently. It seems like I will need to fix the travis pipeline for this to work...
> 
> but the PRs have to be made against the `develop` branch, maybe that is the problem. Could you please change both of the PRs against develop? Thank you.

Did a rebase against develop and that cleared up the CI issue and helped expose a couple of other things that needed to be cleaned-up.

I think one of the last issues is around the SessionStorageInterface changes. I'm not very familiar with what needs to change there. I will need to poke around more. I cannot tell if it's just a configuration thing or something more.

2022-07-02 15:44 UTC, ChadSikorra commented
Ok, after looking at the Symfony 6 upgrade docs, the issue is related to this:

https://github.com/symfony/symfony/blob/6.2/UPGRADE-6.0.md?plain=1#L96-L97

The `session.storage_id` now needs to be `session.storage_factory_id`, which needs to implement `SessionStorageFactoryInterface`. That is easy enough to implement. But it presents an issue in the `SetSessionCookieEventListener` class of this library, which tries to determine the exact `SessionStorageInterface` in use and then executes a custom method on it. Since the session storage is now created via the factory, and cannot be auto-wired in, I'm not sure how this logic would be possible anymore. So something needs to change in that listener, but I'm not sure what a good approach is.

2022-07-03 19:02 UTC, ChadSikorra commented
Well, that was a lot more changes than I would have liked. But I didn't see much of an option with the switch in Symfony 6 for `session.storage_id` to `session.storage_factory_id`. I split the session cookie listener into 2 separate classes with the common functionality in a trait, and a new config option called `session_factory_cookie_event_listener` to enable the new one.

This lets both 5.4 and 6.0+ work depending on config, though it would feel cleaner to drop support for the `session.storage_id` since it was deprecated in 5.4 anyway. But that would break things for anyone using this bundle. Regarding the new event to reset the session storage when using the factory...maybe there's a better approach to be taken there. But this allows the same behavior to be replicated.

Still needs some additional unit tests with the new classes that were added.

2022-07-04 12:35 UTC, Rastusik commented
@ChadSikorra thank you for the contribution! I will look into it soon, but I wonder why the circle ci workflows weren't triggered as in my feature branch... I still will need to fix something

2022-07-04 15:37 UTC, Rastusik commented
Thanks a lot! Yes it had to do with forks, you are the first one who forked this repo :) I will fix the unrelated issues from the other PR and then I hope that circle-ci workflows will be triggered after the fixes and we will see what to do next

2022-07-05 08:52 UTC, Rastusik commented
I think I fixed the pipelines. Could you please rebase your commit on the develop branch and wait for the checks to pass? thank you

2022-07-05 11:06 UTC, Rastusik commented on src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php
> +        if ($config['session_factory_cookie_event_listener']) {
I think this shouldn't be configurable. if symfony 6 is used, this should be enabled by default. what do you say?

2022-07-06 00:41 UTC, ChadSikorra commented on phpstan.tests.neon
> +    reportUnmatchedIgnoredErrors: false
PhpStan sees that we are referencing a constant on a class, and from its perspective the constant value never changes. But it's the Symfony version on the HttpKernel that depends on what version of Symfony is being used :/ So on some Symfony versions it will cause a PhpStan error, and on others it won't. This solves that by ignoring when we don't have an unmatched error.

Another solution is to ignore the tests where I had to add the Symfony version check.

2022-07-06 00:45 UTC, ChadSikorra commented on src/Bridge/Symfony/HttpFoundation/Session/SwooleSessionStorage.php
> +        if (!headers_sent()) {
Without the check I can't unit test the class properly because the constructor attempts to set the session lifetime ini value.

Based on the discussion from the issue you linked, I wonder what the session lifetime translates to in Swoole? Does the current behavior make sense?

2022-07-06 00:47 UTC, ChadSikorra commented on src/Bridge/Symfony/HttpFoundation/Session/SwooleSessionStorageFactory.php
> +        $this->dispatcher->addListener(
Hmm...that's a fair point. The problematic part is that it's an event for a class generated from a factory used by symfony core code. I'll have to check.

2022-07-06 00:49 UTC, ChadSikorra commented on src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php
> +        if ($config['session_factory_cookie_event_listener']) {
I wonder if that might surprise some people who use this? Currently the Swoole session class is only configured if you explicitly add it in config. I agree that if someone installs this bundle though enabling it by default probably makes sense.

2022-07-06 01:04 UTC, ChadSikorra commented on src/Bridge/Symfony/HttpFoundation/Session/SwooleSessionStorage.php
> +        if (!headers_sent()) {
Hmm...I honestly feel like current behavior works, but not how one would expect. I see the way to check headers sent from your link now.

2022-07-06 01:06 UTC, ChadSikorra commented
@Rastusik Thanks for reviewing this! I'm going on vacation shortly and will be out for a week. I will probably not make many changes until a week or so.

2022-07-06 12:29 UTC, Rastusik commented on phpstan.tests.neon
> +    reportUnmatchedIgnoredErrors: false
I see. and where exactly is the error happening? maybe I can come up with other solution

2022-07-06 12:39 UTC, Rastusik commented on src/Bridge/Symfony/HttpFoundation/Session/SwooleSessionStorage.php
> +        if (!headers_sent()) {
btw where did you see the headers_sent usage? I wasn't able to find it

2022-07-06 12:44 UTC, Rastusik commented on src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php
> +        if ($config['session_factory_cookie_event_listener']) {
I think it would be more user friendly to do it automatically when the swoole sessionis activated.

2022-07-06 12:44 UTC, Rastusik commented on src/Bridge/Symfony/HttpFoundation/Session/SwooleSessionStorageFactory.php
> +        $this->dispatcher->addListener(
fair point

2022-07-06 14:39 UTC, ChadSikorra commented on phpstan.tests.neon
> +    reportUnmatchedIgnoredErrors: false
It's in this test:

https://github.com/pixelfederation/swoole-bundle/pull/27/files#diff-1956cb4205d3c2ce2a939bc6557c108a84fac1335b6b99105b3a36d74b68f581R11-R21

2022-07-06 14:47 UTC, ChadSikorra commented on src/Bridge/Symfony/HttpFoundation/Session/SwooleSessionStorage.php
> +        if (!headers_sent()) {
I meant in the Symfony implementation of their native session storage, they do it here:

https://github.com/symfony/symfony/blob/123b1651c4a7e219ba59074441badfac65525efe/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php#L134-L136

Perhaps the session ini setting should just be removed from the listener since setting the session lifetime like this doesn't make sense in the context of Swoole? What do you think?

2022-07-26 14:57 UTC, Rastusik commented
@ChadSikorra hey! how about your vacation? could you please rebase your branch on the `php81` branch from this repo? I updated the CircleCI pipeline to run with PHP 8.1. it will be needed to squash all the commits and to change the commit message into standardized form. will you find time for this or should I do this by pulling your changes into my branch?

2022-07-27 15:25 UTC, Rastusik commented
closed via #30

2022-07-27 15:25 UTC, closed without merging